import nodemailer from 'nodemailer';
import chalk from 'chalk';
import { config } from 'dotenv';

config();

const outputFile = 'output.csv';

const mailConfig = {
    host: process.env.MAIL_HOST,
    port: process.env.MAIL_PORT,
    secure: process.env.MAIL_SECURE === 'true', // true for 465, false for other ports
    auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS
    }
}

// --- Email Details ---
const mailOptions = {
    from: process.env.MAIL_USER, // Sender address
    to: 'iamsainath07@gmail.com', // List of receivers
    subject: 'Code Review Summary CSV', // Subject line
    text: 'Please find attached the code review summary CSV.', // Plain text body
    html: '<b>Hello,</b><p>Please find attached the code review summary CSV.</p>', // HTML body (optional)
    attachments: [
        {
            filename: 'code_review_summary.csv', // Optional: filename seen by recipient
            path: outputFile // Path to the file generated by csv-writer
        }
    ]
};

export async function sendMail() {
    // Create a transporter object using SMTP transport
    const transporter = nodemailer.createTransport(mailConfig);
    // Send mail with defined transport object
    const info = await transporter.sendMail(mailOptions);
    console.log(chalk.green('Message sent: %s', info.messageId));
}